[book]
authors = ["NilPointer Software", "NightNutSky"]
language = "ru"
multilingual = false
src = "src"
title = "Bot Designer for Discord - RU Wiki"

[output.html]
theme = "src/theme"
default-theme = "bdfd"
preferred-dark-theme = "bdfd"
git-repository-url = "https://github.com/NightNutSky/bdfd-wiki"
input-404 = "404.md"
site-url = "/bdfd-wiki/"

[output.html.search]
boost-title = 4  
